/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "surface-dim": "#dad9e1",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3fa",
        "surface-container": "#eeedf4",
        "surface-container-high": "#e9e7ef",
        "surface-container-highest": "#e3e1e9",
        "on-surface": "#1a1b21",
        "on-surface-variant": "#444651",
        "inverse-surface": "#2f3036",
        "inverse-on-surface": "#f1f0f7",
        "outline": "#757682",
        "outline-variant": "#c5c5d3",
        "surface-tint": "#4059aa",
        "primary": "#00236f",
        "on-primary": "#ffffff",
        "primary-container": "#1e3a8a",
        "on-primary-container": "#90a8ff",
        "inverse-primary": "#b6c4ff",
        "secondary": "#516070",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e4f8",
        "on-secondary-container": "#576676",
        "tertiary": "#4b1c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6e2c00",
        "on-tertiary-container": "#f39461",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed": "#00164e",
        "on-primary-fixed-variant": "#264191",
        "secondary-fixed": "#d5e4f8",
        "secondary-fixed-dim": "#b9c8db",
        "on-secondary-fixed": "#0e1d2b",
        "on-secondary-fixed-variant": "#3a4858",
        "tertiary-fixed": "#ffdbcb",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-fixed-variant": "#773205",
        "background": "#faf8ff",
        "on-background": "#1a1b21",
        "surface-variant": "#e3e1e9",
      },
      borderRadius: {
        DEFAULT: "8px",
        lg: "8px",
        xl: "8px",
        "2xl": "8px",
        "3xl": "8px",
        full: "9999px",
      },
      boxShadow: {
        DEFAULT: "0 1px 3px rgba(30, 41, 59, 0.04), 0 1px 2px rgba(30, 41, 59, 0.02)",
        sm: "0 1px 2px rgba(30, 41, 59, 0.03)",
        md: "0 4px 6px -1px rgba(30, 41, 59, 0.04), 0 2px 4px -1px rgba(30, 41, 59, 0.02)",
        lg: "0 10px 15px -3px rgba(30, 41, 59, 0.04), 0 4px 6px -2px rgba(30, 41, 59, 0.02)",
        xl: "0 20px 25px -5px rgba(30, 41, 59, 0.03), 0 10px 10px -5px rgba(30, 41, 59, 0.02)",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "48px",
        xl: "64px",
        gutter: "24px",
        "container-max": "1200px",
        "grid-24": "24px",
      },
      fontFamily: {
        display: ["Noto Sans Thai", "Inter", "sans-serif"],
        sans: ["Noto Sans Thai", "Inter", "sans-serif"],
        sarabun: ["Sarabun", "sans-serif"],
      },
      fontSize: {
        display: ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "card-number": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "validation": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
